### ISSUE TITLE
Proxy host is not configurable and cannot be used off-host from homebridge

### ISSUE THREAD

**Issue by srector13** [jordanryanmoore/homebridge-alexa-player#21]
![Screen Shot 2020-11-16 at 4 44 05 PM](https://user-images.githubusercontent.com/29721860/99317041-fa6b3700-282a-11eb-897b-a636f9126e7e.png)
### Description
I am receiving the following error which is expected to get the Amazon login cookie, however, when I select the link or type it in manually, it says the page is not valid.

### Expected Behavior
Should launch a place to login and generate the cookie

### Logs
Failed to initialize. Error: You can try to get the cookie manually by opening http://localhost:35625/ with your browser.
    at /usr/local/lib/node_modules/alexa-remote2/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/usr/local/lib/node_modules/alexa-remote2/node_modules/alexa-cookie2/lib/proxy.js:362:30)
    at Object.onceWrapper (events.js:416:28)
    at Server.emit (events.js:310:20)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

**Comment by jordanryanmoore** [comment]
Can you provide the following details:

* The OS and version that homebridge is running on.
* Is the Safari browser you're using running on the same Mac as homebridge?

**Comment by srector13** [comment]
I'm on version 1.2.3. My homebridge instance is running on a raspberry pi and I use Homebridge UI to configure it. I installed your plugin using the built in terminal on Homebridge UI through Safari on my Mac and then enabled debug mode. I'm just not sure how to authorize the plugin.

**Comment by jordanryanmoore** [comment]
Ok, the problem is that right now the proxy hostname isn't configurable, and it's assuming your browser and homebridge are running on the same host. I'm working on some changes to address that, but in the mean time, to get this working you would need to use a browser that's on your Raspberry Pi itself to open that URL.

**Comment by srector13** [comment]
Okay, no problem. I know this plugin is still in development so no rush.

**Comment by srector13** [comment]
I know you have closed this but just wanted to let you know that the new authentication works great. I was able to plug in my homebridge servers IP and a port and authenticate via my Mac's browser.
