### ISSUE TITLE
can not get cookie when running in docker on Synology as there is no browse to open the link in

### ISSUE THREAD

**Issue by scooter306** [jordanryanmoore/homebridge-alexa-player#24]
### Description
can not get cookie when running in docker on Synology as there is no browser to open the link in

### Logs
No logs

### Screenshots
no screenshot cause no browser :)

### Additional Context
need a way to get the stuff by command line somehow

**Comment by jordanryanmoore** [comment]
This is a dupe of #21 and was fixed in release 0.2.0.
